In [49]:
from datetime import datetime
import xarray as xr
import numpy as np
from global_land_mask import globe
import os

def create_lsm(latmin, latmax, lonmin, lonmax):
     """Creates a land-sea mask (land=1, sea=0) in 0.1 deg x 0.1 deg resolution
     for the chosen area.
     """
     lat = np.linspace(latmin,latmax, (latmax-latmin)*10+1, dtype = np.float32)
     lon = np.linspace(lonmin,lonmax, (lonmax - lonmin)*10+1, dtype = np.float32)
     longrid, latgrid = np.meshgrid(lon,lat)
     lsm = globe.is_land(latgrid, longrid)
   
     return lsm, latgrid, longrid






In [51]:

#output 
#OUTPUT_PATH = '/home/pietaril/Documents/data/unc_cov_matrices'
OUTPUT_PATH = '/scratch/project_462000459/maija/data/masks'


latmin = 30
latmax = 35
lonmin = -10
lonmax = 0

# latmin = 30.0
# latmax = 75.0
# lonmin = -15.0
# lonmax = 40.0

#fname = f"lsm_lat{latmin}_{latmax}_lon{lonmin}_{lonmax}"


lsm, latgrid, longrid = create_lsm(latmin, latmax, lonmin, lonmax)

In [52]:
lsm

array([[False, False, False, ...,  True,  True,  True],
       [False, False, False, ...,  True,  True,  True],
       [False, False, False, ...,  True,  True,  True],
       ...,
       [False, False, False, ...,  True,  True,  True],
       [False, False, False, ...,  True,  True,  True],
       [False, False, False, ...,  True,  True,  True]])

See if we can use np.ogrid as Laia does


In [43]:
# create a grid of coordinates
res = 0.1
grid_xy = np.ogrid[lonmin:lonmax+res:res, latmin:latmax+res:res]
grid_x, grid_y = grid_xy[0].reshape(1,-1)[0], grid_xy[1][0]
coords = np.array([(i,j) for i in grid_x for j in grid_y])
lon, lat = coords[:,0], coords[:,1]


SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (2332232323.py, line 3)

In [35]:
lon.shape

(5252,)

In [36]:
grid_x.shape

(101,)

In [24]:
grid_y.shape

(100,)

In [41]:
np.meshgrid(grid_y, grid_x)

[array([[30. , 30.1, 30.2, ..., 34.9, 35. , 35.1],
        [30. , 30.1, 30.2, ..., 34.9, 35. , 35.1],
        [30. , 30.1, 30.2, ..., 34.9, 35. , 35.1],
        ...,
        [30. , 30.1, 30.2, ..., 34.9, 35. , 35.1],
        [30. , 30.1, 30.2, ..., 34.9, 35. , 35.1],
        [30. , 30.1, 30.2, ..., 34.9, 35. , 35.1]]),
 array([[-10. , -10. , -10. , ..., -10. , -10. , -10. ],
        [ -9.9,  -9.9,  -9.9, ...,  -9.9,  -9.9,  -9.9],
        [ -9.8,  -9.8,  -9.8, ...,  -9.8,  -9.8,  -9.8],
        ...,
        [ -0.2,  -0.2,  -0.2, ...,  -0.2,  -0.2,  -0.2],
        [ -0.1,  -0.1,  -0.1, ...,  -0.1,  -0.1,  -0.1],
        [  0. ,   0. ,   0. , ...,   0. ,   0. ,   0. ]])]

In [38]:
globe.is_land(lat, lon)

array([False, False, False, ...,  True,  True,  True])

In [47]:
lat2 = np.linspace(latmin,latmax, (latmax-latmin)*10+1, dtype = np.float32)
lon2 = np.linspace(lonmin,lonmax, (lonmax - lonmin)*10+1, dtype = np.float32)
lat2
lon2

array([-10. ,  -9.9,  -9.8,  -9.7,  -9.6,  -9.5,  -9.4,  -9.3,  -9.2,
        -9.1,  -9. ,  -8.9,  -8.8,  -8.7,  -8.6,  -8.5,  -8.4,  -8.3,
        -8.2,  -8.1,  -8. ,  -7.9,  -7.8,  -7.7,  -7.6,  -7.5,  -7.4,
        -7.3,  -7.2,  -7.1,  -7. ,  -6.9,  -6.8,  -6.7,  -6.6,  -6.5,
        -6.4,  -6.3,  -6.2,  -6.1,  -6. ,  -5.9,  -5.8,  -5.7,  -5.6,
        -5.5,  -5.4,  -5.3,  -5.2,  -5.1,  -5. ,  -4.9,  -4.8,  -4.7,
        -4.6,  -4.5,  -4.4,  -4.3,  -4.2,  -4.1,  -4. ,  -3.9,  -3.8,
        -3.7,  -3.6,  -3.5,  -3.4,  -3.3,  -3.2,  -3.1,  -3. ,  -2.9,
        -2.8,  -2.7,  -2.6,  -2.5,  -2.4,  -2.3,  -2.2,  -2.1,  -2. ,
        -1.9,  -1.8,  -1.7,  -1.6,  -1.5,  -1.4,  -1.3,  -1.2,  -1.1,
        -1. ,  -0.9,  -0.8,  -0.7,  -0.6,  -0.5,  -0.4,  -0.3,  -0.2,
        -0.1,   0. ], dtype=float32)

In [48]:
np.meshgrid(lat2, lon2)

[array([[30. , 30.1, 30.2, ..., 34.8, 34.9, 35. ],
        [30. , 30.1, 30.2, ..., 34.8, 34.9, 35. ],
        [30. , 30.1, 30.2, ..., 34.8, 34.9, 35. ],
        ...,
        [30. , 30.1, 30.2, ..., 34.8, 34.9, 35. ],
        [30. , 30.1, 30.2, ..., 34.8, 34.9, 35. ],
        [30. , 30.1, 30.2, ..., 34.8, 34.9, 35. ]], dtype=float32),
 array([[-10. , -10. , -10. , ..., -10. , -10. , -10. ],
        [ -9.9,  -9.9,  -9.9, ...,  -9.9,  -9.9,  -9.9],
        [ -9.8,  -9.8,  -9.8, ...,  -9.8,  -9.8,  -9.8],
        ...,
        [ -0.2,  -0.2,  -0.2, ...,  -0.2,  -0.2,  -0.2],
        [ -0.1,  -0.1,  -0.1, ...,  -0.1,  -0.1,  -0.1],
        [  0. ,   0. ,   0. , ...,   0. ,   0. ,   0. ]], dtype=float32)]